version: "3.4"
services:
  ss-warehouse-api:
    build:
      network: host
      context: .
      dockerfile: Ikv.ScreenshotWarehouse.Api/Dockerfile
    network_mode: "host"
    environment:
      CloudinaryApiKey: ${CloudinaryApiKey}
      CloudinaryApiSecret: ${CloudinaryApiSecret}
      CloudinaryCloudName: ${CloudinaryCloudName}
      IKV_JWT_SECRET: ${IKV_JWT_SECRET}
      IKVDBCONNSTRING: ${IKVDBCONNSTRING}
    ports:
      - "80:80"
    volumes:
      - /ikv-nginx/files:/app/files/